name: happy_chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  dio: ^5.9.0
  mqtt_client: ^10.11.1
  shared_preferences: ^2.5.3
  otp_autofill: ^4.1.0
  pinput: ^5.0.2
  flutter_svg: ^2.2.1
  shamsi_date: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1
  build_runner: ^2.8.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: vazirB
      fonts:
        - asset: assets/fonts/Vazirmatn-Bold.ttf

    - family: vazirM
      fonts:
        - asset: assets/fonts/Vazirmatn-Medium.ttf

    - family: vazirR
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
